blank_issues_enabled: false
contact_links:
  - name: CloudQuery Central Issues Tracker
    url: https://github.com/cloudquery/cloudquery/issues
    about: Please file any issue with regards to any of CloudQuery repo in the main repository with the right labels.
  - name: CloudQuery Discord Support
    url: https://cloudquery.io/discord
    about: Join our discord to get live support from us and the community.
